styles:
  templates:
    layoutRootPath: EXT:rlt3_pure_package/Resources/Private/ContentElements/Layouts
    partialRootPath: EXT:rlt3_pure_package/Resources/Private/ContentElements/Partials
    templateRootPath: EXT:rlt3_pure_package/Resources/Private/ContentElements/Templates
  content:
    textmedia:
      maxW: 1200
      maxWInText: 600
      linkWrap:
        lightboxEnabled: true
        lightboxCssClass: lightbox
